export enum CondicaoClinica {
  ESTAVEL = 'ESTAVEL',
  INTERNADO_UTI_NEONATAL = 'INTERNADO_UTI_NEONATAL',
  INTERNADO_UNIDADE_INTERMEDIARIA = 'INTERNADO_UNIDADE_INTERMEDIARIA',
  CUIDADOS_INTENSIVOS = 'CUIDADOS_INTENSIVOS',
  ISOLAMENTO = 'ISOLAMENTO',
  POS_CIRURGICO = 'POS_CIRURGICO',
  PATOLOGIA_ASSOCIADA = 'PATOLOGIA_ASSOCIADA',
}
