package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DoadoraAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoadoraAllPropertiesEquals(Doadora expected, Doadora actual) {
        assertDoadoraAutoGeneratedPropertiesEquals(expected, actual);
        assertDoadoraAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoadoraAllUpdatablePropertiesEquals(Doadora expected, Doadora actual) {
        assertDoadoraUpdatableFieldsEquals(expected, actual);
        assertDoadoraUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoadoraAutoGeneratedPropertiesEquals(Doadora expected, Doadora actual) {
        assertThat(actual)
            .as("Verify Doadora auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoadoraUpdatableFieldsEquals(Doadora expected, Doadora actual) {
        assertThat(actual)
            .as("Verify Doadora relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getCartaoSUS()).as("check cartaoSUS").isEqualTo(expected.getCartaoSUS()))
            .satisfies(a -> assertThat(a.getCpf()).as("check cpf").isEqualTo(expected.getCpf()))
            .satisfies(a -> assertThat(a.getDataNascimento()).as("check dataNascimento").isEqualTo(expected.getDataNascimento()))
            .satisfies(a -> assertThat(a.getCep()).as("check cep").isEqualTo(expected.getCep()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getCidade()).as("check cidade").isEqualTo(expected.getCidade()))
            .satisfies(a -> assertThat(a.getEndereco()).as("check endereco").isEqualTo(expected.getEndereco()))
            .satisfies(a -> assertThat(a.getTelefone()).as("check telefone").isEqualTo(expected.getTelefone()))
            .satisfies(a -> assertThat(a.getProfissao()).as("check profissao").isEqualTo(expected.getProfissao()))
            .satisfies(a -> assertThat(a.getTipoDoadora()).as("check tipoDoadora").isEqualTo(expected.getTipoDoadora()))
            .satisfies(a -> assertThat(a.getLocalPreNatal()).as("check localPreNatal").isEqualTo(expected.getLocalPreNatal()))
            .satisfies(a -> assertThat(a.getResultadoVDRL()).as("check resultadoVDRL").isEqualTo(expected.getResultadoVDRL()))
            .satisfies(a -> assertThat(a.getResultadoHBsAg()).as("check resultadoHBsAg").isEqualTo(expected.getResultadoHBsAg()))
            .satisfies(a -> assertThat(a.getResultadoFTAabs()).as("check resultadoFTAabs").isEqualTo(expected.getResultadoFTAabs()))
            .satisfies(a -> assertThat(a.getResultadoHIV()).as("check resultadoHIV").isEqualTo(expected.getResultadoHIV()))
            .satisfies(a ->
                assertThat(a.getTransfusaoUltimos5Anos()).as("check transfusaoUltimos5Anos").isEqualTo(expected.getTransfusaoUltimos5Anos())
            )
            .satisfies(a -> assertThat(a.getDataRegistro()).as("check dataRegistro").isEqualTo(expected.getDataRegistro()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoadoraUpdatableRelationshipsEquals(Doadora expected, Doadora actual) {
        // empty method
    }
}
